### ISSUE TITLE
Class PayU does not exist

### ISSUE THREAD

**Issue by Green2Matter** [PayU-EMEA/plugin_magento_24#22]
Magento 2.4.4-p1 (php8.1)
When trying to open in backend Reports - Abandoned carts, there's a following error:
`{"0":"Class \"PayU\\PaymentGateway\\Plugin\\Block\\Widget\\Button\\Toolbar\" does not exist","1":"#1 Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor() called at [vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php:54]\n#2 Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:100]\n#3 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]\n#4 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php:174]\n#5 Magento\\Framework\\Interception\\PluginList\\PluginList->getPlugin() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:119]\n#6 Magento\\Backend\\Block\\Widget\\Button\\Toolbar\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#7 Magento\\Backend\\Block\\Widget\\Button\\Toolbar\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Backend\/Block\/Widget\/Button\/Toolbar\/Interceptor.php:22]\n#8 Magento\\Backend\\Block\\Widget\\Button\\Toolbar\\Interceptor->pushButtons() called at [vendor\/magento\/module-backend\/Block\/Widget\/Container.php:124]\n#9 Magento\\Backend\\Block\\Widget\\Container->_prepareLayout() called at [vendor\/magento\/module-backend\/Block\/Widget\/Grid\/Container.php:103]\n#10 Magento\\Backend\\Block\\Widget\\Grid\\Container->_prepareLayout() called at [vendor\/magento\/framework\/View\/Element\/AbstractBlock.php:272]\n#11 Magento\\Framework\\View\\Element\\AbstractBlock->setLayout() called at [vendor\/magento\/framework\/View\/Layout.php:781]\n#12 Magento\\Framework\\View\\Layout->createBlock() called at [vendor\/magento\/module-reports\/Controller\/Adminhtml\/Report\/Shopcart\/Abandoned.php:36]\n#13 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#14 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#15 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#16 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Reports\/Controller\/Adminhtml\/Report\/Shopcart\/Abandoned\/Interceptor.php:23]\n#17 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#18 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#19 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#20 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#21 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:145]\n#22 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#23 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#24 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Reports\/Controller\/Adminhtml\/Report\/Shopcart\/Abandoned\/Interceptor.php:32]\n#25 Magento\\Reports\\Controller\\Adminhtml\\Report\\Shopcart\\Abandoned\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#26 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#27 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#28 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#30 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#31 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#32 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#33 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#34 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:30]\n","url":"\/admin_111111\/reports\/report_shopcart\/abandoned\/key\/42a9ea0d94a8ce724cbba2f17db9b35246a33abbecdfb19d2d27fb62460e33e5\/","script_name":"\/admin_111111\/reports\/report_shopcart\/abandoned\/key\/42a9ea0d94a8ce724cbba2f17db9b35246a33abbecdfb19d2d27fb62460e33e5\/","report_id":"325a6f85390b8ec4f5a6c2f56cca324b7ecd209a5c53af5a2689e02ae8414fd4"}
`
Also Store - Order Status page is affected as it opened as empty page. After disabling extension, all came back to normal.

**Comment by regdos** [comment]
@Green2Matter 
Please in file Toolbar.php change namespace from `Payu\PaymentGateway\Plugin\Block\Widget\Button` to `PayU\PaymentGateway\Plugin\Block\Widget\Button`and check if the error still shows up.

**Comment by Green2Matter** [comment]
Amended:
```
namespace PayU\PaymentGateway\Plugin\Block\Widget\Button; <- line 3
 * @package PayU\PaymentGateway\Plugin\Block\Widget\Button <- line 14
```
So far looks ok...

**Comment by Green2Matter** [comment]
But nor a long. I've just noticed following error which prevented products from being added to cart:
`[2022-10-20T05:18:34.842352+00:00] main.CRITICAL: Error: Cannot instantiate interface PayU\PaymentGateway\Api\PayUMcpExchangeRateResolverInterface in /home/www/sklepy/mag/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /home/www/sklepy/mag/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#1 /home/www/sklepy/mag/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create()
#2 /home/www/sklepy/mag/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get()
#3 /home/www/sklepy/mag/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create()
#4 /home/www/sklepy/mag/vendor/magento/framework/Event/ObserverFactory.php(33): Magento\Framework\ObjectManager\ObjectManager->get()
#5 /home/www/sklepy/mag/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\Framework\Event\ObserverFactory->get()
#6 /home/www/sklepy/mag/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch()
#7 /home/www/sklepy/mag/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch()
#8 /home/www/sklepy/mag/vendor/magento/module-quote/Model/Quote/TotalsCollector.php(181): Magento\Framework\Event\Manager\Proxy->dispatch()
#9 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\Quote\TotalsCollector->collect()
#10 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->___callParent()
#11 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->Magento\Framework\Interception\{closure}()
#12 /home/www/sklepy/mag/generated/code/Magento/Quote/Model/Quote/TotalsCollector/Interceptor.php(23): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->___callPlugins()
#13 /home/www/sklepy/mag/vendor/magento/module-quote/Model/Quote.php(2007): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->collect()
#14 /home/www/sklepy/mag/vendor/magento/module-checkout/Model/Cart.php(592): Magento\Quote\Model\Quote->collectTotals()
#15 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\Cart->save()
#16 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\Cart\Interceptor->___callParent()
#17 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\Cart\Interceptor->Magento\Framework\Interception\{closure}()
#18 /home/www/sklepy/mag/generated/code/Magento/Checkout/Model/Cart/Interceptor.php(32): Magento\Checkout\Model\Cart\Interceptor->___callPlugins()
#19 /home/www/sklepy/mag/vendor/magento/module-checkout/Controller/Cart/Add.php(129): Magento\Checkout\Model\Cart\Interceptor->save()
#20 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Controller\Cart\Add->execute()
#21 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Cart\Add\Interceptor->___callParent()
#22 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Cart\Add\Interceptor->Magento\Framework\Interception\{closure}()
#23 /home/www/sklepy/mag/generated/code/Magento/Checkout/Controller/Cart/Add/Interceptor.php(23): Magento\Checkout\Controller\Cart\Add\Interceptor->___callPlugins()
#24 /home/www/sklepy/mag/vendor/magento/framework/App/Action/Action.php(111): Magento\Checkout\Controller\Cart\Add\Interceptor->execute()
#25 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#26 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Cart\Add\Interceptor->___callParent()
#27 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Cart\Add\Interceptor->Magento\Framework\Interception\{closure}()
#28 /home/www/sklepy/mag/generated/code/Magento/Checkout/Controller/Cart/Add/Interceptor.php(32): Magento\Checkout\Controller\Cart\Add\Interceptor->___callPlugins()
#29 /home/www/sklepy/mag/vendor/magento/framework/App/FrontController.php(245): Magento\Checkout\Controller\Cart\Add\Interceptor->dispatch()
#30 /home/www/sklepy/mag/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#31 /home/www/sklepy/mag/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#32 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#33 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#34 /home/www/sklepy/mag/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#35 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#36 /home/www/sklepy/mag/vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php(145): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#37 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(135): Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch()
#38 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}()
#39 /home/www/sklepy/mag/generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php(23): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins()
#40 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch()
#41 /home/www/sklepy/mag/vendor/swissup/module-amp/Plugin/Framework/FrontController.php(48): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#42 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(135): Swissup\Amp\Plugin\Framework\FrontController->aroundDispatch()
#43 /home/www/sklepy/mag/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#44 /home/www/sklepy/mag/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#45 /home/www/sklepy/mag/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#46 /home/www/sklepy/mag/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#47 /home/www/sklepy/mag/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#48 {main} [] []`
